### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by aethel-tail** [Tsuk1ko/ff14-cn-sign-in#1]
/usr/lib/node_modules/ff14-cn-sign-in/index.js:28
  async signIn() {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/ff14-cn-sign-in/bin/ff14csi:4:16)

**Comment by Tsuk1ko** [comment]
确保你安装的 node ≥ 8，或直接下载使用构建好的可执行文件

另外请下载或更新到 v1.0.2，修复了签到问题
